<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>NebulaRaid.Benchmarks</RootNamespace>
    <AssemblyName>NebulaRaid.Benchmarks</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NebulaRaid.Core\NebulaRaid.Core.csproj" />
  </ItemGroup>
</Project>

