<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>NebulaRaid.Demo</RootNamespace>
    <AssemblyName>NebulaRaid.Demo</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NebulaRaid.Core\NebulaRaid.Core.csproj" />
  </ItemGroup>
</Project>

